version: 2

sources:
  - name: incidents
    database: "{{ env_var('DBT_BIGQUERY_PROJECT')  }}"
    schema: "{{ env_var('DBT_BIGQUERY_DATASET')  }}"
    tables:
      - name: incidents_data
      - name: incidents_coordinates
      - name: zones

models:
  - name: fct_incidents_coordinates
    description: > 
      Data about the locations of the incidents
      precision of approximately 10KM
    columns:
      - name: id
        data_type: string
        tests:
          - not_null:
              severity: warn

          - unique:
              severity: warn

      - name: lon
        data_type: float
        tests:
          - not_null:
              severity: warn

      - name: lat
        data_type: float
        tests:
          - not_null:
              severity: warn

      - name : village
        data_type: string

      - name : county
        data_type: string

      - name : state
        data_type: string

      - name : postcode
        data_type: string

      - name : country
        data_type: string

      - name : country_code
        data_type: string

      - name : state_district
        data_type: string

      - name : municipality
        data_type: string

      - name : city_district
        data_type: string

      - name : city
        data_type: string

      - name : town
        data_type: string


  - name : stg_incidents_data
    description: >
      Containes flattened and cleaned incidents_data before enrichment
    columns: 
      - name: id
        data_type: string
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: icon_category
        description: >
          Code of the reported incident cause
            0= Unknown
            1= Accident
            2= Fog
            3= DangerousConditions
            4= Rain
            5= Ice
            6= Jam
            7= LaneClosed
            8= RoadClosed
            9= RoadWorks
            10= Wind
            11= Flooding
            14= BrokenDownVehicle
        tests:
          - not_null:
              severity: warn

          - accepted_values:
              values: "{{ var('incident_causes') }}"
              severity: warn

      - name: incident_cause

      - name: delay_category
        description: >
          The magnitude of delay associated with an incident
          0= Unknown
          1= Minor
          2= Moderate
          3= Major
          4= Undefined
        tests:
          - not_null:
              severity: warn
          - accepted_values:
              values: "{{ var('incident_delay') }}"
              severity: warn
      - name: magnitude_of_delay

      - name: start_time
      - name: end_time
      - name: from
      - name: to
      - name: length
      - name: delay
      - name: probability_of_occurence
        description: >
          Enumeration string specifying the likelihood of the occurring incident.
          certain
          probable
          risk_of
          improbable

      - name: number_of_reports
        description: >
          The number of reports given by actual end-users.

      - name: last_report_time
        description: >
          The date when the last time the incident was reported

      - name: description
        description: >
          The description of the event

      - name: code
        description: >
          Event alert code
